// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2boTdbSNw0gaBvj4tgUC96espsFDvts4',
    appId: '1:728438298477:web:4f142d94eb2d7e161aac64',
    messagingSenderId: '728438298477',
    projectId: 'isoftronics-b82cd',
    authDomain: 'isoftronics-b82cd.firebaseapp.com',
    storageBucket: 'isoftronics-b82cd.appspot.com',
    measurementId: 'G-T044D2Q87E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJa5_iHxWsurSxFTWApA9FZ0PS6wp75v8',
    appId: '1:728438298477:android:c441eef78fd7c85b1aac64',
    messagingSenderId: '728438298477',
    projectId: 'isoftronics-b82cd',
    storageBucket: 'isoftronics-b82cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmMATPGGxPIpCxunH3Rs-j1MdB2mJtS0I',
    appId: '1:728438298477:ios:b85a47e24010a3281aac64',
    messagingSenderId: '728438298477',
    projectId: 'isoftronics-b82cd',
    storageBucket: 'isoftronics-b82cd.appspot.com',
    iosBundleId: 'com.example.crudOperartions',
  );
}
